spring.application.name=travel-brief

spring.cloud.openfeign.client.config.frankfurter.url=https://api.frankfurter.app
spring.cloud.openfeign.client.config.open-meteo.url=https://api.open-meteo.com/v1
spring.cloud.openfeign.client.config.rest-countries.url=https://api.restcountries.com/countries/v5

clients.rest-countries.key=rc_live_21a7cc39daf6478fabb7e877c140bf17
