spring:
  application:
    name: travel-brief

clients:
  rest-countries:
    url: https://api.restcountries.com/countries/v5
    key: rc_live_21a7cc39daf6478fabb7e877c140bf17
  open-meteo:
    url: https://api.open-meteo.com/v1
  frankfurter:
    url: https://api.frankfurter.app